# Generated by Django 2.2 on 2019-05-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionOfDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('collectionPicture', models.ImageField(upload_to=None)),
                ('designer', models.ManyToManyField(to='designers.Designer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_account.UserAccount')),
            ],
        ),
    ]
