# Generated by Django 2.2 on 2019-05-10 17:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateForTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbb', to='tag.Tag')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')])),
                ('lastName', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z]*$')])),
                ('username', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9]*$')])),
                ('password', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(regex='')])),
                ('isDesigner', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('tag', models.ManyToManyField(through='user_account.RateForTag', to='tag.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='ratefortag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aa', to='user_account.UserAccount'),
        ),
    ]
