# Generated by Django 2.2 on 2019-05-10 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
        ('tag', '0001_initial'),
        ('designers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('isValid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=150, unique=True)),
                ('view', models.IntegerField(default=0)),
                ('total_rate', models.IntegerField(default=0)),
                ('contact_date', models.DateField(auto_now_add=True)),
                ('contact_time', models.TimeField(auto_now_add=True)),
                ('comments', models.ManyToManyField(through='designs.CommentForDesign', to='user_account.UserAccount')),
                ('designer', models.ManyToManyField(related_name='designs', to='designers.Designer')),
            ],
        ),
        migrations.CreateModel(
            name='RateForDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_design', to='designs.Design')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_design', to='user_account.UserAccount')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='rate_user',
            field=models.ManyToManyField(related_name='designs', through='designs.RateForDesign', to='user_account.UserAccount'),
        ),
        migrations.AddField(
            model_name='design',
            name='tag',
            field=models.ManyToManyField(related_name='designs', to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='commentfordesign',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_design', to='designs.Design'),
        ),
        migrations.AddField(
            model_name='commentfordesign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_design', to='user_account.UserAccount'),
        ),
    ]
