# Generated by Django 2.2 on 2019-05-10 17:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentForDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=500)),
                ('isvalid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField(validators=[django.core.validators.RegexValidator(regex='')])),
                ('city', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='')])),
                ('address', models.CharField(max_length=150)),
                ('comments', models.ManyToManyField(related_name='Designer1', through='designers.CommentForDesigner', to='user_account.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='RateForDesigner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_designer', to='designers.Designer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_for_designer', to='user_account.UserAccount')),
            ],
        ),
        migrations.CreateModel(
            name='DesignerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
                ('description', models.CharField(max_length=500)),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designer_records', to='designers.Designer')),
            ],
        ),
        migrations.AddField(
            model_name='designer',
            name='rates',
            field=models.ManyToManyField(related_name='Designer2', through='designers.RateForDesigner', to='user_account.UserAccount'),
        ),
        migrations.AddField(
            model_name='designer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='designer', to='user_account.UserAccount'),
        ),
        migrations.AddField(
            model_name='commentfordesigner',
            name='designer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_designer', to='designers.Designer'),
        ),
        migrations.AddField(
            model_name='commentfordesigner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_for_designer', to='user_account.UserAccount'),
        ),
    ]
